### ISSUE TITLE
AttributeError: module 'dedupe' has no attribute 'Dedupe' - same as Issue #623

### ISSUE THREAD

**Issue by talikarng** [dedupeio/dedupe#640] opened 2018-02-24 03:49 UTC
I have had the same issue (AttributeError: module 'dedupe' has no attribute 'Dedupe') in python in Ubuntu and Anaconda. Same as #623 

Here is the output from

`import dedupe`
`dedupe.__file__`

run in Spyder under the Anaconda distribution

`In [2]: runfile('/home/user/Desktop/untitled2.py', wdir='/home/user/Desktop') Reloaded modules: future, future.builtins, future.builtins.iterators, future.utils, future.builtins.misc, unidecode, unidecode.x000, unidecode.x020, unidecode.x022, unidecode.x003`

**Comment by fgregg** [comment] 2018-04-30 18:05
As you said, this is a dupe of #623

**Closed by fgregg** 2018-04-30 18:05 UTC
