### ISSUE TITLE
Inference time of RecordLink is too slow

### ISSUE THREAD

**Issue by QQSkill** [dedupeio/dedupe#1094] opened 2022-09-08 10:20 UTC
Why my RecordLink is too slow when sample data is so small
![Screenshot_21](https://user-images.githubusercontent.com/35594088/189097954-4fb2f561-9588-424c-88b7-c4232f90112a.png)

**Comment by NickCrews** [comment] 2022-09-08 21:32
Can you please give a script that totally reproduces this? Important missing details are:
1. What is the actual data
2. what are your variable definitions
3. what do your format_data_dedupe() functions look like

This might be unlikely, but is it slow if you do it a second time? I'm wondering if there is a slow startup time from some slow imports or something.

**Comment by QQSkill** [comment] 2022-09-09 06:24
![image](https://user-images.githubusercontent.com/35594088/189284648-657487a9-fd72-4502-aedb-477855e5e09d.png)
![image](https://user-images.githubusercontent.com/35594088/189284508-9f807f1a-b58f-4ca1-a5c5-5945ee4322bd.png)
![image](https://user-images.githubusercontent.com/35594088/189284579-bfdf800d-89f1-4af0-b064-38c9548f2719.png)
 
They are details about my script. Second run deduper.join() still like that, i don't know why it take so long with super small data

**Comment by NickCrews** [comment] 2022-09-09 17:36
Nothing pops out to me as obviously wrong there. One thing that I don't think is related to this problem, but FYI, is when you convert nans to None, it's never a good idea to modify a container while iterating over it.

I guess one question is how much of a problem this actually is? Like 3 seconds isn't that slow for most offline tasks. Are you worried that it's not going to scale well? Because perhaps that 3 seconds is all a constant time overhead, and if you go up to 10,000 records it still only takes 10 seconds. Have you actually tried at larger number of data to see how it scales? Perhaps run time for 100, 1000, 10k records?

If it actually is a problem, then I think the next step would be for you to actually share a reproducible script or notebook and we could take a look.

**Comment by QQSkill** [comment] 2022-09-12 09:14
Thank you, i realized dedupe run with 200,000 pairs with 4s and 60 pairs with 3s, probally dedupe spend time for initializing predicate block.

**Comment by NickCrews** [comment] 2022-09-12 21:36
Or for spawning multiprocessing or something. Probably this should get closed as it is expected. Please re-open or start a new issue if something changes.

**Closed** 2022-09-19 02:52 UTC
