### ISSUE TITLE
Can we use the logistic regression parmeters to do feature selection?

### ISSUE THREAD

**Issue by arthur-rocha** [dedupeio/dedupe#758] opened 2019-07-17 19:43 UTC
As far I know, if we have the parameters estimators, the standart errors and the distribution we can test the parameters to do feature selection. Anyone know if that is possible in this case?

**Comment by fgregg** [comment] 2019-07-21 18:55
This seems to be a question about logistic regression. That's out of scope for this project.

**Closed by fgregg** 2019-07-21 18:55 UTC

**Comment by arthur-rocha** [comment] 2019-07-22 11:22
Thanks for the response @fgregg but...
Actually, this is a question about Dedupe's model in general... I know that can be done with regular use of logistic regression, but what I'm asking is if that makes sense to do feature selection on the dedupe's model... 
The parameters of the logistic model can be used for that? Another thing, can I get the parameter's standard errors somehow with the dedupe's output?

**Comment by fgregg** [comment] 2019-07-22 12:08
sure, it can make sense. the details of how to do feature selection are out of scope for this project.
